# Generated by Django 5.2.1 on 2025-06-19 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_benhnhan_nam_sinh'),
    ]

    operations = [
        migrations.AddField(
            model_name='pkb',
            name='ds_kham',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phieu_kham', to='accounts.dskham'),
        ),
    ]
