# Generated by Django 5.2.1 on 2025-07-08 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_thuoc_cach_dung_mac_dinh_thuoc_han_su_dung'),
    ]

    operations = [
        migrations.AddField(
            model_name='pkb',
            name='nguoi_lap_phieu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phieu_kham_da_lap', to=settings.AUTH_USER_MODEL, verbose_name='người lập phiếu'),
        ),
        migrations.AlterField(
            model_name='benhnhan',
            name='gioi_tinh',
            field=models.CharField(blank=True, choices=[('M', 'Nam'), ('F', 'Nữ')], max_length=1, null=True, verbose_name='giới tính'),
        ),
    ]
