# Generated by Django 5.2.1 on 2025-07-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_pkb_nguoi_lap_phieu_alter_benhnhan_gioi_tinh'),
    ]

    operations = [
        migrations.AddField(
            model_name='taikhoan',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default_avatar.jpg', null=True, upload_to='avatars/'),
        ),
    ]
