# Generated by Django 5.2.1 on 2025-06-11 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenhNhan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=100, verbose_name='họ tên')),
                ('dia_chi', models.CharField(blank=True, max_length=255, verbose_name='địa chỉ')),
                ('nam_sinh', models.DateField(blank=True, null=True, verbose_name='năm sinh')),
                ('gioi_tinh', models.CharField(blank=True, choices=[('M', 'Nam'), ('F', 'Nữ'), ('O', 'Khác')], max_length=1, null=True, verbose_name='giới tính')),
            ],
            options={
                'verbose_name': 'Bệnh Nhân',
                'verbose_name_plural': 'Các Bệnh Nhân',
                'ordering': ['ho_ten'],
            },
        ),
        migrations.CreateModel(
            name='CachDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_cach_dung', models.CharField(max_length=100, unique=True, verbose_name='tên cách dùng')),
            ],
            options={
                'verbose_name': 'Cách Dùng Thuốc',
                'verbose_name_plural': 'Các Cách Dùng Thuốc',
                'ordering': ['ten_cach_dung'],
            },
        ),
        migrations.CreateModel(
            name='DonViTinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_don_vi_tinh', models.CharField(max_length=50, unique=True, verbose_name='tên đơn vị tính')),
            ],
            options={
                'verbose_name': 'Đơn Vị Tính',
                'verbose_name_plural': 'Các Đơn Vị Tính',
                'ordering': ['ten_don_vi_tinh'],
            },
        ),
        migrations.CreateModel(
            name='LoaiBenh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_loai_benh', models.CharField(max_length=100, unique=True, verbose_name='tên loại bệnh')),
            ],
            options={
                'verbose_name': 'Loại Bệnh',
                'verbose_name_plural': 'Các Loại Bệnh',
                'ordering': ['ten_loai_benh'],
            },
        ),
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('ho_ten', models.CharField(blank=True, default='', max_length=150, verbose_name='họ tên')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='địa chỉ email')),
                ('ten_dang_nhap', models.CharField(max_length=150, unique=True, verbose_name='tên đăng nhập')),
                ('is_active', models.BooleanField(default=True, verbose_name='kích hoạt')),
                ('is_staff', models.BooleanField(default=False, help_text='Chỉ định user có thể đăng nhập vào trang admin hay không.', verbose_name='nhân viên')),
                ('groups', models.ManyToManyField(blank=True, help_text='Các vai trò mà người dùng này thuộc về. Người dùng sẽ có tất cả các quyền được gán cho mỗi vai trò của họ.', related_name='taikhoan_set', to='auth.group', verbose_name='các vai trò (groups)')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Các quyền được gán trực tiếp cho người dùng này.', related_name='taikhoan_permissions_set', to='auth.permission', verbose_name='quyền trực tiếp')),
            ],
            options={
                'verbose_name': 'Tài Khoản',
                'verbose_name_plural': 'Các Tài Khoản',
                'ordering': ['ho_ten', 'ten_dang_nhap'],
            },
        ),
        migrations.CreateModel(
            name='PKB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_kham', models.DateField(verbose_name='ngày khám')),
                ('trieu_chung', models.TextField(blank=True, verbose_name='triệu chứng')),
                ('benh_nhan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.benhnhan', verbose_name='bệnh nhân')),
                ('loai_benh_chuan_doan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.loaibenh', verbose_name='loại bệnh chẩn đoán')),
            ],
            options={
                'verbose_name': 'Phiếu Khám Bệnh',
                'verbose_name_plural': 'Các Phiếu Khám Bệnh',
                'ordering': ['-ngay_kham'],
            },
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_thanh_toan', models.DateTimeField(auto_now_add=True, verbose_name='ngày thanh toán')),
                ('tien_kham', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='tiền khám')),
                ('tien_thuoc', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='tiền thuốc')),
                ('phieu_kham_benh', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hoa_don', to='accounts.pkb', verbose_name='phiếu khám bệnh')),
            ],
            options={
                'verbose_name': 'Hóa Đơn',
                'verbose_name_plural': 'Các Hóa Đơn',
                'ordering': ['-ngay_thanh_toan'],
            },
        ),
        migrations.CreateModel(
            name='Thuoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_thuoc', models.CharField(max_length=100, unique=True, verbose_name='tên thuốc')),
                ('so_luong_ton', models.PositiveIntegerField(default=0, verbose_name='số lượng tồn')),
                ('don_gia', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='đơn giá')),
                ('don_vi_tinh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.donvitinh', verbose_name='đơn vị tính')),
            ],
            options={
                'verbose_name': 'Thuốc',
                'verbose_name_plural': 'Các Loại Thuốc',
                'ordering': ['ten_thuoc'],
            },
        ),
        migrations.CreateModel(
            name='DSKham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_kham', models.DateField(verbose_name='ngày khám')),
                ('benh_nhan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.benhnhan', verbose_name='bệnh nhân')),
            ],
            options={
                'verbose_name': 'Danh Sách Khám',
                'verbose_name_plural': 'Các Danh Sách Khám',
                'ordering': ['ngay_kham', 'id'],
                'unique_together': {('ngay_kham', 'benh_nhan')},
            },
        ),
        migrations.CreateModel(
            name='ChiTietPKB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong_ke', models.PositiveIntegerField(verbose_name='số lượng kê')),
                ('cach_dung_chi_dinh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.cachdung', verbose_name='cách dùng chỉ định')),
                ('phieu_kham_benh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet_don_thuoc', to='accounts.pkb', verbose_name='phiếu khám bệnh')),
                ('thuoc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.thuoc', verbose_name='thuốc')),
            ],
            options={
                'verbose_name': 'Chi Tiết Đơn Thuốc',
                'verbose_name_plural': 'Các Chi Tiết Đơn Thuốc',
                'unique_together': {('phieu_kham_benh', 'thuoc')},
            },
        ),
    ]
