# Generated by Django 5.2.1 on 2025-06-04 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenhNhan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=100)),
                ('dia_chi', models.CharField(max_length=255, null=True)),
                ('nam_sinh', models.DateField(null=True)),
                ('gioi_tinh', models.CharField(max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CachDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_cach_dung', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DonViTinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_don_vi_tinh', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LoaiBenh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_loai_benh', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VaiTro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_vai_tro', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DSKham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_kham', models.DateField()),
                ('id_benh_nhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.benhnhan')),
            ],
        ),
        migrations.CreateModel(
            name='PKB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_kham', models.DateField()),
                ('trieu_chung', models.CharField(max_length=255, null=True)),
                ('id_benh_nhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.benhnhan')),
                ('id_loai_benh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.loaibenh')),
            ],
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tien_kham', models.FloatField()),
                ('tien_thuoc', models.FloatField()),
                ('tong_tien', models.FloatField()),
                ('id_pkb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.pkb')),
            ],
        ),
        migrations.CreateModel(
            name='Thuoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_thuoc', models.CharField(max_length=100)),
                ('so_luong', models.IntegerField(null=True)),
                ('gia', models.FloatField()),
                ('hsd', models.DateField(null=True)),
                ('id_cach_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.cachdung')),
                ('id_don_vi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.donvitinh')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietPKB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl', models.IntegerField(null=True)),
                ('id_pkb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.pkb')),
                ('id_thuoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.thuoc')),
            ],
        ),
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('ho_ten', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('ten_dang_nhap', models.CharField(max_length=50, unique=True)),
                ('mat_khau', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='tai_khoan_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='tai_khoan_set', to='auth.permission', verbose_name='user permissions')),
                ('id_vai_tro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.vaitro')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
