# Generated by Django 5.2.1 on 2025-06-13 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dskham',
            options={'ordering': ['ngay_kham', 'id'], 'verbose_name': 'Danh Sách Chờ Khám', 'verbose_name_plural': 'Các Danh Sách Chờ Khám'},
        ),
        migrations.AlterModelOptions(
            name='pkb',
            options={'ordering': ['-ngay_kham', '-id'], 'verbose_name': 'Phiếu Khám Bệnh', 'verbose_name_plural': 'Các Phiếu Khám Bệnh'},
        ),
        migrations.AddField(
            model_name='cachdung',
            name='mo_ta',
            field=models.TextField(blank=True, null=True, verbose_name='mô tả'),
        ),
        migrations.AlterField(
            model_name='benhnhan',
            name='dia_chi',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='địa chỉ'),
        ),
        migrations.AlterField(
            model_name='chitietpkb',
            name='cach_dung_chi_dinh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chi_tiet_theo_cach_dung', to='accounts.cachdung', verbose_name='cách dùng chỉ định'),
        ),
        migrations.AlterField(
            model_name='chitietpkb',
            name='thuoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chi_tiet_su_dung', to='accounts.thuoc', verbose_name='thuốc'),
        ),
        migrations.AlterField(
            model_name='dskham',
            name='benh_nhan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lich_kham', to='accounts.benhnhan', verbose_name='bệnh nhân'),
        ),
        migrations.AlterField(
            model_name='hoadon',
            name='phieu_kham_benh',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hoa_don_lien_ket', to='accounts.pkb', verbose_name='phiếu khám bệnh'),
        ),
        migrations.AlterField(
            model_name='hoadon',
            name='tien_thuoc',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='tiền thuốc'),
        ),
        migrations.AlterField(
            model_name='pkb',
            name='benh_nhan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phieu_kham_benh', to='accounts.benhnhan', verbose_name='bệnh nhân'),
        ),
        migrations.AlterField(
            model_name='pkb',
            name='loai_benh_chuan_doan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pkb_theo_loai_benh', to='accounts.loaibenh', verbose_name='loại bệnh chẩn đoán'),
        ),
        migrations.AlterField(
            model_name='pkb',
            name='trieu_chung',
            field=models.TextField(blank=True, default='', verbose_name='triệu chứng'),
        ),
        migrations.AlterField(
            model_name='taikhoan',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Các vai trò mà người dùng này thuộc về.', related_name='tai_khoan_groups', to='auth.group', verbose_name='các vai trò'),
        ),
        migrations.AlterField(
            model_name='taikhoan',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Các quyền được gán trực tiếp cho người dùng này.', related_name='tai_khoan_user_permissions', to='auth.permission', verbose_name='quyền trực tiếp'),
        ),
        migrations.AlterField(
            model_name='thuoc',
            name='don_gia',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='đơn giá'),
        ),
        migrations.AlterField(
            model_name='thuoc',
            name='don_vi_tinh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thuoc_theo_don_vi', to='accounts.donvitinh', verbose_name='đơn vị tính'),
        ),
        migrations.CreateModel(
            name='QuyDinhValue',
            fields=[
                ('ma_quy_dinh', models.CharField(choices=[('MAX_PATIENTS_PER_DAY', 'Số bệnh nhân tối đa mỗi ngày'), ('BASE_EXAMINATION_FEE', 'Tiền khám cơ bản')], max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='mã quy định')),
                ('gia_tri', models.CharField(help_text='Giá trị của quy định.', max_length=255, verbose_name='giá trị')),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True, verbose_name='ngày cập nhật')),
                ('nguoi_cap_nhat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quy_dinh_value_cap_nhat', to=settings.AUTH_USER_MODEL, verbose_name='người cập nhật')),
            ],
            options={
                'verbose_name': 'Giá Trị Quy Định',
                'verbose_name_plural': 'Các Giá Trị Quy Định',
                'ordering': ['ma_quy_dinh'],
            },
        ),
    ]
