# Generated by Django 5.2.2 on 2025-06-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taikhoan',
            name='mat_khau',
        ),
        migrations.AlterField(
            model_name='benhnhan',
            name='gioi_tinh',
            field=models.CharField(choices=[('M', 'Nam'), ('F', 'Nữ')], default='M', max_length=3, null=True),
        ),
    ]
