# Generated by Django 5.2.1 on 2025-06-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_dskham_options_alter_pkb_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benhnhan',
            name='nam_sinh',
            field=models.IntegerField(blank=True, null=True, verbose_name='năm sinh'),
        ),
    ]
