# Generated by Django 5.2.2 on 2025-06-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_taikhoan_mat_khau_alter_benhnhan_gioi_tinh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaitro',
            name='ten_vai_tro',
            field=models.CharField(choices=[('manager', 'Quản lý'), ('med_staff', 'Nhân viên y tế'), ('patient', 'Bệnh nhân')], default='patient', max_length=50),
        ),
    ]
