# Generated by Django 5.2.2 on 2025-06-05 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_vaitro_ten_vai_tro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taikhoan',
            old_name='id_vai_tro',
            new_name='vai_tro',
        ),
    ]
