# Generated by Django 5.2.2 on 2025-06-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_id_vai_tro_taikhoan_vai_tro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaitro',
            name='ten_vai_tro',
            field=models.CharField(choices=[('manager', 'Quản lý'), ('med_staff', 'Nhân viên y tế')], default='patient', max_length=50),
        ),
    ]
