# Generated by Django 5.2.1 on 2025-06-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_pkb_ds_kham'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quydinhvalue',
            name='ngay_cap_nhat',
        ),
        migrations.RemoveField(
            model_name='quydinhvalue',
            name='nguoi_cap_nhat',
        ),
        migrations.AlterField(
            model_name='quydinhvalue',
            name='gia_tri',
            field=models.PositiveIntegerField(help_text='Giá trị số của quy định.', verbose_name='giá trị'),
        ),
    ]
