# Generated by Django 5.2.1 on 2025-06-19 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_quydinhvalue_ngay_cap_nhat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thuoc',
            name='cach_dung_mac_dinh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thuoc_theo_cach_dung', to='accounts.cachdung', verbose_name='cách dùng mặc định'),
        ),
        migrations.AddField(
            model_name='thuoc',
            name='han_su_dung',
            field=models.DateField(blank=True, null=True, verbose_name='hạn sử dụng'),
        ),
    ]
