# Generated by Django 5.2.1 on 2025-06-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_vaitro_ten_vai_tro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaitro',
            name='ten_vai_tro',
            field=models.CharField(choices=[('manager', 'Quản lý'), ('med_staff', 'Nhân viên y tế')], default='med_staff', max_length=50),
        ),
    ]
